---
title: "individual1"
author: "Kellan Bouwman"
date: "10/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Part 2

# Question 1

```{r}
# dplyr
library(dplyr)
# ggplot2
library(ggplot2)
#Libary
library(tidyr)
#Libary
library(readxl)
defense <- read_excel('cyclonesFootball2019.xlsx', sheet='Defensive')

defClean <- defense %>%
              mutate(across(c("Name", "Opponent_Opponent"), as.factor)) %>%
              mutate_if(is.character, as.numeric, na.rm = TRUE)
str(defClean)

defClean %>%
  pivot_longer(Tackles_Solo:Pass_PB, names_to = "stat", values_to = "Score") -> defClean

print(defClean)
```


# Question 2

```{r}
ggplot(defClean, aes(x = Score)) + geom_histogram(bins = 6) + facet_wrap(~stat, scales = 'free_y')
ggplot(defClean, aes(x = Score)) +  geom_bar() + facet_wrap(~stat, scales = 'free_y')
```


# Question 3

```{r}
defClean %>%
  filter(stat == "Tackles_Solo" & Opponent_Opponent == "UNI") -> SoloUNI
defClean %>%
  filter(stat == "Tackles_Solo" & Opponent_Opponent == "UNI") -> SoloND

ggplot(SoloUNI, aes(x=Score, y=Score)) + geom_point()
ggplot(SoloND, aes(x=Score, y=Score)) + geom_point()
```

